const D=window.AFT_DATA;const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const S=()=>JSON.parse(localStorage.getItem('aft2')||'{}');const save=x=>localStorage.setItem('aft2',JSON.stringify({...S(),...x}));let currentCase=0,promptIndex=0,caseScore=0,timer=null,seconds=1200;
function esc(t=''){return String(t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function page(id){$$('.page').forEach(x=>x.classList.toggle('active',x.id==='p-'+id));$$('[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===id));location.hash=id;window.scrollTo({top:0,behavior:'smooth'});if(id==='oral'&&!$('#examLog').dataset.started)startCase(0);if(id==='quick')newQuick();}
function days(){const d=S().examDate;if(!d)return null;return Math.max(0,Math.ceil((new Date(d+'T12:00:00')-Date.now())/86400000))}
function renderHeader(){const s=S(),name=s.name||'Kollege';$$('[data-name]').forEach(x=>x.textContent=name);$$('[data-days]').forEach(x=>x.textContent=days()??'–');$('#profileName').value=s.name||'';$('#examDate').value=s.examDate||'';const mastered=(s.mastered||[]).length;$('#metricMastered').textContent=mastered;$('#metricCases').textContent=s.cases||0;$('#metricStreak').textContent=(s.streak||1)+' d';const pct=Math.min(100,Math.round(mastered/D.domains.length*70+Math.min(30,(s.cases||0)*3)));$('#metricProgress').textContent=pct+'%';$('#progressBar').style.width=pct+'%'}
function renderDomains(filter=''){const q=filter.toLowerCase();const arr=D.domains.filter(x=>(x.title+' '+x.desc+' '+x.tags.join(' ')).toLowerCase().includes(q));$('#domainGrid').innerHTML=arr.map(x=>`<div class="card topic"><div class="icon">${x.icon}</div><div style="flex:1"><div class="eyebrow">${x.priority==='hot'?'HOT TOPIC':'CURRICULUM'}</div><h3>${x.title}</h3><div class="muted small">${x.desc}</div><div class="tagrow">${x.tags.map(t=>`<span class="tag source">${t}</span>`).join('')}${x.priority==='hot'?'<span class="tag hot">2026 relevant</span>':''}</div><div class="list" style="margin-top:11px">${x.pearls.map(p=>`<div class="small">✓ ${p}</div>`).join('')}</div><div style="margin-top:12px"><button class="btn ghost" onclick="toggleMaster('${x.id}')">${(S().mastered||[]).includes(x.id)?'✓ Beherrscht':'Als beherrscht markieren'}</button></div></div></div>`).join('')||'<div class="card">Keine Treffer.</div>'}
function toggleMaster(id){let a=S().mastered||[];a=a.includes(id)?a.filter(x=>x!==id):[...a,id];save({mastered:a});renderDomains($('#globalSearch').value);renderHeader();toast('Fortschritt gespeichert')}
function renderRadar(){$('#radar').innerHTML=D.hotTopics.map(x=>`<div class="row"><strong class="small">${x.topic}</strong><div><div class="bar"><span style="width:${x.score}%"></span></div><div class="muted small" style="margin-top:4px">${x.note}</div></div><small>${x.place}</small></div>`).join('')}
function renderCases(){$('#caseList').innerHTML=D.cases.map((c,i)=>`<button class="item" style="text-align:left;cursor:pointer" onclick="startCase(${i});page('oral')"><strong>${c.title}</strong><span class="muted small">${c.domain} · ${c.level} · ${c.prompts.length} Frage${c.prompts.length>1?'n':''}</span></button>`).join('')}
function renderDrugs(q=''){q=q.toLowerCase();$('#drugRows').innerHTML=D.drugs.filter(x=>x.join(' ').toLowerCase().includes(q)).map(x=>`<tr><td><strong>${x[0]}</strong></td><td>${x[1]}</td><td>${x[2]}</td></tr>`).join('')}
function renderSources(){$('#sourceGrid').innerHTML=D.sources.map(s=>`<div class="card"><div class="eyebrow">${s.type}</div><h3>${s.name}</h3><p class="muted small">${s.note}</p><a class="btn ghost" href="${s.url}" target="_blank" rel="noopener">Quelle öffnen ↗</a></div>`).join('')}
const quickBank=[...D.domains.flatMap(d=>d.pearls.map((p,i)=>({q:`${d.title}: Nenne einen prüfungsrelevanten Kernpunkt.`,a:p,src:d.tags.join(' · ')}))),...D.hotTopics.map(h=>({q:`Wie würdest du in 60 Sekunden das Thema „${h.topic}“ strukturieren?`,a:h.note,src:'MEDI-LEARN Hot-Topic-Snapshot 2026'}))];let quick=null;
function newQuick(){quick=quickBank[Math.floor(Math.random()*quickBank.length)];$('#quickQ').textContent=quick.q;$('#quickA').classList.add('hidden');$('#quickA').innerHTML=`<strong>Muster-Kernpunkt:</strong><br>${quick.a}<div class="tagrow"><span class="tag source">${quick.src}</span></div>`}
function revealQuick(){$('#quickA').classList.remove('hidden')}
function startCase(i){currentCase=i;promptIndex=0;caseScore=0;seconds=1200;clearInterval(timer);const c=D.cases[i],log=$('#examLog');log.dataset.started='1';log.innerHTML=`<div class="bubble examiner"><strong>Prüfer:</strong><br>${c.intro}</div>`;$('#caseTitle').textContent=c.title;$('#caseMeta').textContent=`${c.domain} · ${c.level}`;$('#caseInput').disabled=false;$('#caseInput').value='';examiner(c.prompts[0].q);timer=setInterval(()=>{seconds=Math.max(0,seconds-1);renderTimer();if(!seconds)finishCase()},1000);renderTimer()}
function examiner(t){$('#examLog').insertAdjacentHTML('beforeend',`<div class="bubble examiner"><strong>Prüfer:</strong><br>${t}</div>`);$('#examLog').scrollTop=$('#examLog').scrollHeight}
function renderTimer(){const m=String(Math.floor(seconds/60)).padStart(2,'0'),s=String(seconds%60).padStart(2,'0');$('#timer').textContent=`${m}:${s}`}
function submitCase(){const input=$('#caseInput'),text=input.value.trim();if(!text)return;const p=D.cases[currentCase].prompts[promptIndex],low=text.toLowerCase(),hits=p.keys.filter(k=>low.includes(k));caseScore+=hits.length;$('#examLog').insertAdjacentHTML('beforeend',`<div class="bubble user">${esc(text)}</div><div class="bubble examiner"><strong>Coach:</strong> ${hits.length>=5?'Sehr gute Struktur.':hits.length>=3?'Solide. Einige Kernpunkte fehlen noch.':'Zu knapp oder zu wenig strukturiert.'}<br><br><strong>Musterstruktur:</strong> ${p.model}<br><span class="small" style="color:#94a3b8">Erkannte Kernpunkte: ${hits.length}/${p.keys.length}</span></div>`);input.value='';promptIndex++;if(promptIndex<D.cases[currentCase].prompts.length)examiner(D.cases[currentCase].prompts[promptIndex].q);else finishCase();$('#examLog').scrollTop=$('#examLog').scrollHeight}
function finishCase(){clearInterval(timer);const c=D.cases[currentCase];$('#caseInput').disabled=true;const pct=Math.min(100,Math.round(45+caseScore*4));examiner(`Fall beendet. Demo-Score ${pct} %. Entscheidend ist nicht das Stichwort-Zählen, sondern eine klare klinische Priorisierung. Die spätere AI-Version soll semantisch bewerten.`);const s=S();save({cases:(s.cases||0)+1});renderHeader()}
function nextCase(){startCase((currentCase+1)%D.cases.length)}
function globalSearch(v){renderDomains(v);if(v.trim())page('curriculum')}
function saveProfile(){save({name:$('#profileName').value.trim()||'Kollege',examDate:$('#examDate').value});renderHeader();toast('Profil gespeichert');page('dashboard')}
function toast(t){let n=document.createElement('div');n.className='toast';n.textContent=t;document.body.appendChild(n);setTimeout(()=>n.remove(),1800)}
function resetAll(){if(confirm('Lernfortschritt wirklich zurücksetzen?')){const s=S();localStorage.setItem('aft2',JSON.stringify({name:s.name||'',examDate:s.examDate||''}));renderHeader();renderDomains();toast('Fortschritt zurückgesetzt')}}
function init(){renderHeader();renderDomains();renderRadar();renderCases();renderDrugs();renderSources();newQuick();$('#globalSearch').addEventListener('input',e=>globalSearch(e.target.value));$('#drugSearch').addEventListener('input',e=>renderDrugs(e.target.value));const hash=location.hash.slice(1);page(['dashboard','curriculum','quick','oral','radar','drugs','sources','profile'].includes(hash)?hash:'dashboard')}
window.addEventListener('DOMContentLoaded',init);