window.AFT_DATA={
  sources:[
    {id:'mdh',name:'MD Horizonte – Anästhesiologie Repetitorium',type:'Curriculum',note:'Öffentliches Themenprogramm als Orientierung für die Breite des Curriculums.',url:'https://md-horizonte.de/anaesthesiologie-repetitorium/'},
    {id:'annecke',name:'Annecke & Hohn – Facharztprüfung Anästhesiologie, 2. Aufl.',type:'Prüfungsstruktur',note:'Öffentlich beschriebene Gliederung: Grundlagen, prä-, intra- und postoperativ, Kinder, ambulant, Notfall/Intensiv.',url:'https://books.google.com/books/about/Facharztpr%C3%BCfung_An%C3%A4sthesiologie.html?id=U47ZEAAAQBAJ'},
    {id:'praxis',name:'Praxis der Anästhesiologie – Wilhelm / Meyer-Frießem',type:'Praxiswissen',note:'Leitlinienorientierte Kapitelstruktur und Fallorientierung als didaktische Referenz.',url:'https://link.springer.com/book/9783662731123'},
    {id:'medi',name:'MEDI-LEARN Facharzt-Prüfungsprotokolle',type:'Prüfungsrealität',note:'Öffentlich sichtbare Protokollzusammenfassungen 2026 als Hot-Topic-Snapshot; keine Häufigkeitsstatistik.',url:'https://www.medi-learn.de/pruefungsprotokolle/facharztpruefung'}
  ],
  domains:[
    {id:'preop',icon:'🩺',title:'Präoperativ',desc:'Anamnese, Risiko, Nüchternheit, Dauermedikation, Aufklärung, Frailty',tags:['Annecke/Hohn','Praxis'],priority:'high',pearls:['OP- und patientenspezifisches Risiko trennen','Untersuchungen nur bei Konsequenz für Management','Antikoagulation, OSA, Frailty und Delir-Risiko aktiv adressieren']},
    {id:'airway',icon:'🫁',title:'Airway Management',desc:'Prädiktion, RSI, schwieriger Atemweg, wach, CICO, Extubation',tags:['MD Horizonte','MEDI-LEARN 2026'],priority:'hot',pearls:['Oxygenierung ist das Ziel','Plan A/B/C/D vor Einleitung','CICO früh benennen und eFONA nicht verzögern']},
    {id:'physio',icon:'🧪',title:'Physiologie & BGA',desc:'Atmung, Kreislauf, Säure-Basen, O₂-Transport, V/Q',tags:['MD Horizonte'],priority:'high',pearls:['PaCO₂ ↔ alveoläre Ventilation','O₂-Transport aus Hb, Sättigung und Herzzeitvolumen denken','BGA immer mit klinischem Kontext interpretieren']},
    {id:'pharma',icon:'💊',title:'Pharmakologie',desc:'Hypnotika, Opioide, Relaxantien, Katecholamine, TIVA/TCI',tags:['MD Horizonte','Praxis'],priority:'high',pearls:['Wirkmechanismus + Hämodynamik + Organabhängigkeit','Dosisanpassung anhand Patient und Kontext erklären','Nebenwirkung → Erkennung → Therapie']},
    {id:'monitor',icon:'📈',title:'Monitoring & Arbeitsplatz',desc:'Standardmonitoring, invasiv, TEE/POCUS-Basis, Narkosegerät',tags:['MD Horizonte','Praxis','MEDI-LEARN 2026'],priority:'hot',pearls:['Monitoring an Risiko koppeln','Messfehler vor Pathophysiologie ausschließen','Ultraschall gewinnt in aktuellen Protokollen sichtbar an Bedeutung']},
    {id:'general',icon:'💤',title:'Allgemeinanästhesie',desc:'Einleitung, Aufrechterhaltung, TIVA, inhalativ, Awareness, Emergence',tags:['MD Horizonte','Praxis','MEDI-LEARN 2026'],priority:'hot',pearls:['Induktion an Hämodynamik anpassen','Awareness-Risiken aktiv nennen','Extubation ist eigener Hochrisiko-Schritt']},
    {id:'regional',icon:'🧠',title:'Regionalanästhesie',desc:'Spinal, Epidural, Plexus, Ultraschall, Antikoagulation, LAST',tags:['MD Horizonte','Praxis','MEDI-LEARN 2026'],priority:'hot',pearls:['Indikation/Kontraindikationen strukturiert','Anatomie + Ultraschall + Komplikationen','LAST sofort erkennen und Algorithmus abrufen']},
    {id:'hemo',icon:'🫀',title:'Kreislauf & Gerinnung',desc:'Schock, Volumen, Vasopressoren, Blutung, Transfusion, POC-Gerinnung',tags:['MD Horizonte','Praxis'],priority:'high',pearls:['Schocktyp und Perfusionsziel benennen','Blutung: Ursache und Physiologie parallel behandeln','Temperatur, Calcium, pH und Fibrinogen mitdenken']},
    {id:'ob',icon:'🤰',title:'Geburtshilfe',desc:'Sectio, PDK/SPA, Präeklampsie, PPH, schwieriger Atemweg',tags:['MD Horizonte','MEDI-LEARN 2026'],priority:'hot',pearls:['Dringlichkeit der Sectio zuerst klären','Mutter und Kind gleichzeitig denken','PPH und schwieriger Atemweg gehören zusammen geplant']},
    {id:'peds',icon:'🧸',title:'Kinderanästhesie',desc:'Atemweg, Dosisprinzipien, HNO, Notfälle, Medikamentensicherheit',tags:['Annecke/Hohn','MD Horizonte','MEDI-LEARN 2026'],priority:'hot',pearls:['Gewicht, Alter und Atemwegsphysiologie sind zentral','Bradykardie oft Hypoxiezeichen','HNO-Fälle sind prüfungstaugliche Klassiker']},
    {id:'special',icon:'🏥',title:'Spezielle Anästhesie',desc:'Thorax, Kardio, Neuro, HNO, Uro, Gefäß, Adipositas',tags:['MD Horizonte','Praxis'],priority:'high',pearls:['Operationsspezifische Physiologie erklären','Monitoring und postoperative Destination begründen','Komorbidität verändert Technik und Medikamentenwahl']},
    {id:'icu',icon:'🛏️',title:'Intensivmedizin',desc:'Sepsis, ARDS, Niere, Leber, Sedierung, Delir, Organversagen',tags:['Annecke/Hohn','MD Horizonte','MEDI-LEARN 2026'],priority:'hot',pearls:['Problem priorisieren und Organunterstützung strukturieren','Sepsis ist Perfusions- und Infektionsproblem','Reevaluation nach jeder Intervention']},
    {id:'emergency',icon:'🚨',title:'Notfall & Trauma',desc:'ABCDE/cABCDE, Reanimation, Polytrauma, SHT, Anaphylaxie, MH',tags:['MD Horizonte','Annecke/Hohn','MEDI-LEARN 2026'],priority:'hot',pearls:['Team, Prioritäten und Kommunikation benennen','Polytrauma parallel statt seriell denken','Reversible Ursachen aktiv abarbeiten']},
    {id:'pain',icon:'⚡',title:'Schmerz & Postoperativ',desc:'PONV, Akutschmerz, Regionalverfahren, PACU, Komplikationen',tags:['MD Horizonte','Praxis','Annecke/Hohn'],priority:'normal',pearls:['Analgesie multimodal denken','Entlasskriterien aus PACU kennen','Postoperative Komplikation = zuerst ABC']},
    {id:'law',icon:'⚖️',title:'Recht, Sicherheit & Qualität',desc:'Aufklärung, Dokumentation, Medikamentensicherheit, SOP, Hygiene',tags:['Annecke/Hohn','Praxis'],priority:'normal',pearls:['Einwilligung und Dringlichkeit differenzieren','Dokumentation ist Teil der Therapie','Lokale SOP und Leitlinie unterscheiden']}
  ],
  hotTopics:[
    {topic:'Schwieriger Atemweg / RSI',place:'Düsseldorf 2026',score:96,note:'Notsectio, Adipositas, eingeschränkte Mundöffnung, Wachintubation/CICO'},
    {topic:'Geburtshilfe / Sectio / PPH',place:'Düsseldorf & weitere 2026',score:94,note:'Dringlichkeit, Regionalverfahren, Gerinnung, Uterotonika'},
    {topic:'Polytrauma / SHT / Schockraum',place:'Hannover & weitere 2026',score:91,note:'cABCDE, Atemweg, eFAST, BGA, Blutung, Neuroprotektion'},
    {topic:'Prämed / Risiko / Frailty',place:'Düsseldorf 2026',score:86,note:'Geriatrie, Delir, Antikoagulation, präoperative Diagnostik'},
    {topic:'Regional / LAST / Ultraschall',place:'Hannover/Rostock 2026',score:84,note:'Plexus, Sonoanatomie, Toxizität, Rescue'},
    {topic:'Sepsis / Kreislauf',place:'Protokolle 2026',score:80,note:'Definition, Perfusion, Volumen, Vasopressor, Antibiotika'},
    {topic:'Awareness / Narkosetiefe',place:'Hannover 2026',score:73,note:'Risikogruppen, Prävention, Folgen'},
    {topic:'Beatmung / Systeme / V-Q',place:'Protokolle 2026',score:70,note:'Kreissystem, O₂-Bedarf, respiratorische Physiologie'}
  ],
  cases:[
    {id:'ileus',domain:'Notfall',title:'Ileus zur Notfalllaparotomie',level:'Basis → Fortgeschritten',intro:'72-jähriger Patient, Erbrechen, geblähtes Abdomen, OP-Indikation. Kreislauf grenzwertig.',prompts:[
      {q:'Wie strukturieren Sie Ihre präoperative Einschätzung und Vorbereitung?',keys:['aspiration','nüchtern','volumen','bga','laktat','zugang','arter','blut','intensiv','rsi'],model:'Aspirations- und Sepsis-/Hypovolämierisiko benennen → Vitalparameter/BGA/Laktat und Volumenstatus → geeignete Zugänge, Blutprodukte nach Situation, erweitertes Monitoring → Präoxygenierung → RSI mit Backup-Plan → postoperative Destination.'},
      {q:'Nach Einleitung fällt der Blutdruck auf 65/35 mmHg. Wie gehen Sie vor?',keys:['mess','abc','vasopress','norad','volumen','tiefe','blutung','anaphyl','herz','reeval'],model:'Messwert und Perfusion plausibilisieren → ABC und Narkosetiefe → häufige Ursachen systematisch prüfen → Vasopressor/Volumen bzw. ursachenspezifische Therapie → Wirkung unmittelbar reevaluieren.'},
      {q:'Die Intubation gelingt nicht, die Maskenbeatmung wird schwieriger. Was jetzt?',keys:['hilfe','oxygen','versuch','supraglott','cico','efona','front'],model:'Hilfe rufen → Oxygenierung priorisieren → weitere traumatische Versuche begrenzen → optimierte Maskenbeatmung / supraglottischer Rescue → CICO klar erkennen → eFONA nach aktuellem Difficult-Airway-Algorithmus.'}]},
    {id:'notsectio',domain:'Geburtshilfe',title:'Dringliche Sectio bei erwartet schwierigem Atemweg',level:'High Yield',intro:'Adipöse Schwangere, fetale Gefährdung, sehr eingeschränkte Mundöffnung. Sectio wird dringlich.',prompts:[
      {q:'Welche Informationen brauchen Sie sofort, bevor Sie sich für ein Anästhesieverfahren entscheiden?',keys:['dringlichkeit','regional','pd','spinal','airway','aspiration','gerinn','iv','monitor'],model:'Dringlichkeitsgrad und Zeitfenster → vorhandener PDK / neuraxiale Optionen → Gerinnung/Antikoagulation → Atemwegs- und Aspirationsrisiko → Team/Material/Backup inklusive schwieriger Atemweg.'},
      {q:'Wie würden Sie einen erwarteten schwierigen Atemweg in dieser Situation planen?',keys:['oxygen','wach','fiber','video','hilfe','backup','cico','efona'],model:'Oxygenierung und Zeitkritik abwägen → erfahrenes Team und vollständiges Difficult-Airway-Setup → bei geeigneter Situation wache Atemwegssicherung erwägen → klare Rescue- und CICO-Strategie inklusive eFONA.'}]},
    {id:'polytrauma',domain:'Trauma',title:'Polytrauma mit SHT im Schockraum',level:'High Yield',intro:'Motorradunfall, präklinisch intubiert, Hypotonie, Thorax- und Extremitätenverletzungen, SHT.',prompts:[
      {q:'Wie übernehmen Sie den Patienten im Schockraum?',keys:['team','cabcde','tubus','cuff','beatmung','efast','bga','blut','wärme','gerinn'],model:'Strukturierter Team-Handover → cABCDE parallel → Tubuslage/Beatmung verifizieren → Blutungssuche und eFAST → BGA/Kreuzblut/POC-Gerinnung → Wärmeerhalt und zielgerichtete Hämotherapie → SHT-spezifische Sekundärschäden vermeiden.'}]},
    {id:'lv',domain:'Kreislauf',title:'Schwere LV-Dysfunktion vor Hemikolektomie',level:'Fortgeschritten',intro:'Patient mit hochgradig reduzierter EF zur großen abdominellen Operation.',prompts:[
      {q:'Wie planen Sie Monitoring und Einleitung?',keys:['arter','wach','zugang','echo','vasopress','opioid','propofol','etomid','intensiv','ziel'],model:'Hämodynamische Ziele formulieren → arterielle Messung vor Einleitung erwägen → vasoaktive Medikation bereit → titrierte, kreislaufschonende Einleitung → Volumen vorsichtig → ggf. POCUS/erweitertes Monitoring → postoperative Intensivstrategie.'}]},
    {id:'sepsis',domain:'Intensiv',title:'Pneumogene Sepsis mit Schock',level:'High Yield',intro:'Verwirrte Patientin, RR 60/40, Tachykardie, respiratorische Insuffizienz.',prompts:[
      {q:'Was tun Sie in den ersten Minuten?',keys:['abc','oxygen','zugang','laktat','kultur','antibiot','volumen','norad','arter','quelle','reeval'],model:'ABCDE → Oxygenierung/Ventilation und Zugänge → BGA/Laktat, Kulturen ohne relevante Verzögerung → frühe Antibiotikatherapie → vorsichtige perfusionsorientierte Flüssigkeit → Noradrenalin bei persistierender Hypotonie → arterielle Messung, Fokus-/Quellenkontrolle und Reevaluation.'}]},
    {id:'last',domain:'Regional',title:'LAST nach peripherer Regionalanästhesie',level:'Notfall',intro:'Kurz nach Lokalanästhetikagabe: Unruhe, neurologische Symptome, dann Rhythmusstörung.',prompts:[
      {q:'Wie erkennen und behandeln Sie LAST?',keys:['stop','hilfe','airway','oxygen','krampf','lipid','reanimation','dosis'],model:'Lokalanästhetikum stoppen → Hilfe und ABC/Oxygenierung → Krampf behandeln → Lipid-Rescue nach aktuellem Protokoll → Reanimation mit LAST-spezifischen Besonderheiten → Überwachung.'}]},
    {id:'awareness',domain:'Allgemeinanästhesie',title:'Awareness-Risiko bei Notfallnarkose',level:'Prüfungsklassiker',intro:'Hochrisikopatient in zeitkritischer Operation, hämodynamisch instabil.',prompts:[
      {q:'Welche Risikofaktoren und Präventionsmaßnahmen besprechen Sie?',keys:['notfall','sectio','trauma','relax','tiva','monitor','dosierung','gerät','gespräch','dokument'],model:'Risikokonstellation erkennen → sichere Medikamentenzufuhr/Narkosegerät prüfen → adäquate hypnotische Komponente trotz Kreislaufproblem titrieren → Narkosetiefe im Kontext überwachen → bei Verdacht strukturierte Nachbesprechung und Dokumentation.'}]},
    {id:'pedsENT',domain:'Kinder',title:'Kind zur HNO-Operation',level:'High Yield',intro:'Kleinkind zur Tonsillen-/Adenoidchirurgie, Infektanamnese unklar.',prompts:[
      {q:'Welche Risiken klären Sie präoperativ und wie planen Sie den Atemweg?',keys:['infekt','atemweg','alter','gewicht','fasten','blutung','laryngo','broncho','analges','ponv'],model:'Alter/Gewicht und aktuelle Atemwegsinfektion → OSA/obstruktive Symptome → Nüchternheit → Atemweg und perioperative Laryngo-/Bronchospasmus-Risiken → Blutung → kindgerechte Analgesie/PONV-Prophylaxe und postoperative Überwachung.'}]}
  ],
  drugs:[
    ['Propofol','Hypnotikum','Titration; dosisabhängige Hypotonie/Apnoe; TIVA-Kontext'],['Etomidat','Hypnotikum','relative Kreislaufstabilität; Nebennierenrinden-Suppression als Prüfungspunkt'],['Ketamin','Dissoziatives Anästhetikum','Analgesie; Bronchodilatation; sympathoadrenerge Effekte kontextabhängig'],['Rocuronium','Nichtdepolarisierendes Relaxans','rascher Wirkungseintritt; neuromuskuläres Monitoring; Sugammadex'],['Succinylcholin','Depolarisierendes Relaxans','sehr rasch; Hyperkaliämie- und MH-Kontext'],['Sugammadex','Antagonist','Rocuronium/Vecuronium; Blockadetiefe und Dosierung nach Fachinformation'],['Noradrenalin','Vasopressor','vorwiegend α; vasoplegische Hypotonie; Perfusionsziel statt Einzelwert'],['Adrenalin','Katecholamin','α/β; Reanimation und schwere Anaphylaxie'],['Remifentanil','Opioid','ultrakurz; kontextsensitive Steuerbarkeit; Hyperalgesie/Bradykardie beachten'],['Dexmedetomidin','α2-Agonist','Sedierung mit relativ geringer Atemdepression; Bradykardie/Hypotonie']
  ]
};