const COURSE_ORDER=['exam','neurophys','resp','cardiophys','renal','livergi','endocrine','hypnotics','opioids','nmb','volatile','local','adjuvants','vaso','monitoring','transfusion','preopcore','cardiacrisk','pulmrisk','organpreop','meds','fasting','eras','consent','access','induction','vent','fluids','emergence','airway','regionalper','neuraxial','last','lap','thorax','vascular','ent','uro','obgyn','remote','neuro','ortho','pacu','pain','ponv','postcomp','bleed','pedprep','pedind','pedcomp','specialkids','ambulatory','aspiration','shock','anaphylaxis','sepsis','cpr','acs','polytrauma','icu','aki','burns','mh','ards','cases1','cases2','cases3','cases4','cases5','cases6','cases7','cases8','cases9','cases10','protocols','mock1','mock2','final'];
const SOURCE_NOTE=`<div class="callout source"><strong>Quellenstand:</strong> Diese Lektion ist eigenständig formuliert aus den vom Nutzer bereitgestellten Quellen. Annecke/Hohn stammt aus 2020, die Springer-Facharzt-Training-Sonderhefte aus 2019. Zeitkritische Leitlinien-, Dosierungs- und Therapieangaben müssen im weiteren Ausbau gegen den aktuellen Stand geprüft werden.</div>`;
const COURSES={
exam:{phase:'Phase 1 · Grundlagen',title:'Prüfungslogik & Antwortstruktur',intro:'Bevor du Medizin wiederholst, lernst du zuerst, wie du dein Wissen in einer mündlichen Facharztprüfung klinisch verwertbar präsentierst.',sources:['Annecke/Hohn · Kap. 1.1 Prüfungspsychologie','Quellenstand 2020'],sections:[
{id:'ziel',title:'1. Was wird in der Facharztprüfung eigentlich geprüft?',html:`<p class="lead">Die Prüfung ist nicht dafür gedacht, möglichst viele isolierte Fakten abzurufen. In der von Annecke/Hohn beschriebenen Prüfungslogik sollst du zeigen, dass du einen Patienten <strong>eigenverantwortlich, sicher und strukturiert</strong> versorgen kannst.</p><p>Typischer Ausgangspunkt ist eine klinische Situation aus dem Alltag. Daraus entstehen Nachfragen zu Diagnostik, Differenzialdiagnosen, Physiologie, Pharmakologie, Monitoring und Therapie. Deshalb ist unser Lernpfad ebenfalls fallorientiert aufgebaut.</p><div class="callout merke"><strong>Merke:</strong> Eine gute Antwort verbindet drei Ebenen: <b>Situation erkennen → Handlung begründen → Hintergrund erklären.</b></div>`},
{id:'struktur',title:'2. Die universelle Antwortstruktur',html:`<p>Wenn eine Frage offen gestellt wird, brauchst du ein Gerüst. Dieses Gerüst verhindert, dass du dich in Details verlierst.</p><ol><li><strong>Problem in einem Satz benennen.</strong> Was ist die unmittelbare Gefahr oder Kernfrage?</li><li><strong>Prioritäten setzen.</strong> Bei Instabilität zuerst ABC/ABCDE; bei elektiven Fragen zuerst Risiko und Ziel.</li><li><strong>Informationen sammeln.</strong> Anamnese, Untersuchung, Monitoring, Labor/Bildgebung nur soweit sie die Entscheidung beeinflussen.</li><li><strong>Therapie oder Plan formulieren.</strong> Nicht bloß Medikamente nennen, sondern sagen, warum.</li><li><strong>Reevaluation.</strong> Woran erkennst du, ob deine Maßnahme funktioniert?</li><li><strong>Weiteres Vorgehen.</strong> Postoperative Destination, Dokumentation, Teamkommunikation.</li></ol><div class="callout exam"><strong>Prüfersatz:</strong> „Ein 72-jähriger Patient wird nach Einleitung hypotensiv. Was tun Sie?“<br><b>Starke Antwort:</b> „Ich prüfe zuerst, ob der Messwert plausibel ist und ob Zeichen einer Minderperfusion bestehen. Parallel sichere ich ABC, prüfe Narkosetiefe und häufige Ursachen wie Vasodilatation, Hypovolämie, Blutung, Anaphylaxie oder kardiale Ursachen. Dann behandle ich ursachengerecht und reevaluieren unmittelbar.“</div>`},
{id:'kommunikation',title:'3. So sprichst du in der Prüfung',html:`<p>Annecke/Hohn empfiehlt konkrete, zusammenhängende Antworten. Für den Trainer bedeutet das: keine Stichwortsalven. Formuliere vollständige Sätze und beantworte zuerst genau die gestellte Frage.</p><p>Beginne nicht mit zehn Differenzialdiagnosen, wenn der Prüfer nach deiner ersten Maßnahme fragt. Beginne auch nicht mit einer langen Definition, wenn ein instabiler Patient vor dir liegt. <strong>Klinische Priorität schlägt Lexikonwissen.</strong></p><div class="callout cave"><strong>Häufiger Fehler:</strong> Zu viel ungeordnetes Wissen kann neue Nebenthemen öffnen und die Kernfrage unbeantwortet lassen.</div>`},
{id:'unsicher',title:'4. Was tun, wenn du etwas nicht weißt?',html:`<p>Eine überraschende Frage ist nicht automatisch ein Problem. Die Quelle betont, dass der Kandidat eine sichere Lösungsstrategie zeigen soll. Frage nach, wenn die Situation unklar ist, und denke klinisch laut, ohne gefährliche Behauptungen zu erfinden.</p><p>Eine brauchbare Formulierung ist: <em>„Ich bin bei diesem Detail nicht sicher. Für die sichere Patientenversorgung würde ich zunächst … und parallel die konkrete Dosierung/Empfehlung in Fachinformation oder SOP verifizieren.“</em></p><p>Das ist stärker als Raten. In der Medizin ist zu erkennen, wann eine Information verifiziert werden muss, Teil professioneller Kompetenz.</p>`},
{id:'lernen',title:'5. Wie du diesen 0→100-Pfad benutzt',html:`<p>Die Quelle empfiehlt aktives Formulieren anhand konkreter Fälle statt ausschließlich passivem Lesen. Deshalb hat jede Vollkurs-Lektion dieselbe Lernschleife:</p><ol><li>Kurs lesen und verstehen.</li><li>Merksätze ohne Blick auf den Text wiederholen.</li><li>Prüferfragen laut beantworten.</li><li>Mini-Quiz lösen.</li><li>Erst dann die Lektion als abgeschlossen markieren.</li></ol><div class="callout merke"><strong>Deine Regel:</strong> „Gelesen“ ist nicht „gelernt“. Du bist fertig, wenn du die Kernidee in eigenen Worten erklären kannst.</div>${SOURCE_NOTE}`}
],quiz:[
{q:'Was ist bei einer offenen klinischen Prüfungsfrage der stärkste Einstieg?',a:['Sofort alle bekannten Medikamente aufzählen','Das Kernproblem und die Priorität benennen','Mit einer langen Pathophysiologie beginnen','Den Prüfer um eine andere Frage bitten'],c:1,e:'Der klinische Fokus beginnt mit Problem und Priorität; Details folgen strukturiert.'},
{q:'Was ist bei Unsicherheit sinnvoll?',a:['Eine Dosis raten','Schweigen','Unsicherheit benennen, sichere Schritte formulieren und das Detail verifizieren','Das Thema wechseln'],c:2,e:'Sicheres Denken ist prüfungsrelevant; ungesichertes Raten ist es nicht.'},
{q:'Welche Lernmethode passt zur beschriebenen Prüfungsform?',a:['Nur markieren und lesen','Aktives Antworten an klinischen Fällen','Nur Karteikarten ohne Fälle','Nur Multiple Choice'],c:1,e:'Die Quelle empfiehlt aktive Formulierung anhand von Fällen.'}]},

neurophys:{phase:'Phase 1 · Grundlagen',title:'Nervensystem für Anästhesisten',intro:'Du lernst das Nervensystem nicht als Anatomieprüfung, sondern so, dass Pharmakologie, Kreislaufsteuerung, Regionalanästhesie und postoperative Neurologie später logisch werden.',sources:['Annecke/Hohn · Kap. 1.2.1','Quellenstand 2020'],sections:[
{id:'aufbau',title:'1. ZNS, PNS und vegetatives Nervensystem',html:`<p class="lead">Das Nervensystem lässt sich zunächst in <strong>ZNS</strong> (Gehirn und Rückenmark) und <strong>PNS</strong> gliedern. Im PNS unterscheidet man somatische und vegetative Anteile. Das vegetative Nervensystem umfasst Sympathikus, Parasympathikus und enterisches Nervensystem.</p><p>Für die Anästhesie ist diese Einteilung praktisch: Hypnotika und Analgetika wirken zentral, Muskelrelaxanzien an der motorischen Endplatte, Lokalanästhetika an peripheren Nerven, und Katecholamine beeinflussen das vegetative System beziehungsweise dessen Rezeptoren.</p>`},
{id:'autonom',title:'2. Sympathikus und Parasympathikus',html:`<p>Der Sympathikus entspringt thorakolumbal. Präganglionär wird Acetylcholin verwendet, postganglionär überwiegend Noradrenalin. Eine klassische Ausnahme bilden Schweißdrüsen, an denen auch postganglionär Acetylcholin wirkt.</p><p>Der Parasympathikus hat kraniale und sakrale Ursprünge; der N. vagus ist für viele thorakale und abdominale Organe besonders wichtig. Der Transmitter ist Acetylcholin.</p><div class="callout merke"><strong>Prüfungsbrücke:</strong> Wenn du später Atropin, Neostigmin, Noradrenalin oder β₂-Mimetika lernst, denkst du nicht in Medikamentenlisten, sondern in diesem Rezeptorsystem.</div>`},
{id:'transmitter',title:'3. Die zentralen Transmitter',html:`<p>Annecke/Hohn hebt zwei zentrale Gegenspieler hervor: <strong>Glutamat</strong> als wichtigen exzitatorischen Transmitter (unter anderem am NMDA-Rezeptor) und <strong>GABA</strong> als wichtigen inhibitorischen Transmitter.</p><p>Diese Gegenüberstellung erklärt später die Pharmakologie: Viele i.v. Hypnotika verstärken GABAerge Hemmung; Ketamin unterscheidet sich durch seine NMDA-Wirkung.</p>`},
{id:'fasern',title:'4. Warum Nervenfasern unterschiedlich blockiert werden',html:`<p>Periphere Fasern unterscheiden sich in Durchmesser und Myelinisierung. Dadurch unterscheiden sie sich auch in der Empfindlichkeit gegenüber Lokalanästhetika. In der Quelle werden sympathische Fasern früh blockiert, danach Temperatur- und Schmerzfasern; motorische Aα-Fasern sind weniger empfindlich.</p><p>Das erklärt den <strong>Differenzialblock</strong>: Bei einer neuraxialen Analgesie können Schmerz und Sympathikotonus deutlich reduziert sein, während Berührung oder Motorik teilweise erhalten bleiben.</p><div class="callout exam"><strong>Prüfer fragt:</strong> „Warum wird ein Patient nach Spinalanästhesie hypotensiv, bevor eine komplette motorische Blockade vorliegt?“<br>Antwortlogik: frühe sympathische Blockade → Vasodilatation/verminderter venöser Rückstrom → hämodynamische Konsequenz.</div>${SOURCE_NOTE}`}
],quiz:[
{q:'Welcher Transmitter ist im ZNS besonders inhibitorisch?',a:['Glutamat','GABA','Noradrenalin','Dopamin'],c:1,e:'GABA ist ein zentraler inhibitorischer Transmitter.'},
{q:'Welcher Transmitter wirkt präganglionär im Sympathikus?',a:['Acetylcholin','Noradrenalin','Adrenalin','Serotonin'],c:0,e:'Präganglionär wirkt Acetylcholin; postganglionär überwiegend Noradrenalin.'},
{q:'Was erklärt den Differenzialblock bei Regionalanästhesie?',a:['Alle Nervenfasern reagieren identisch','Fasertypen unterscheiden sich in Empfindlichkeit','Nur motorische Fasern werden blockiert','Lokalanästhetika wirken ausschließlich zentral'],c:1,e:'Faserdurchmesser/Myelinisierung und weitere Eigenschaften beeinflussen die Blockadeempfindlichkeit.'}]},

resp:{phase:'Phase 1 · Grundlagen',title:'Atemwege, Lunge & BGA',intro:'Von der Atemwegsanatomie bis zur Blutgasanalyse: Hier entsteht das Fundament für Airway-Management, Beatmung, ARDS, COPD und praktisch jede Intensivfrage.',sources:['Annecke/Hohn · Kap. 1.2.2','Quellenstand 2020'],sections:[
{id:'airway',title:'1. Atemweg: von oben nach unten',html:`<p class="lead">Die oberen Atemwege umfassen in der Quelle Nase, Mund und Rachen. Die unteren Atemwege beginnen am Kehlkopf und reichen über Trachea, Hauptbronchien, Bronchien und Bronchiolen bis zu den respiratorischen Bronchiolen und Alveolen.</p><p>Am Larynx sind Schild-, Ring-, Epiglottis- und Aryknorpel prüfungsrelevant. Motorische und sensible Innervation laufen über Äste des N. vagus. Besonders praktisch: oberhalb der Glottis erfolgt die sensible Versorgung über den N. laryngeus superior, unterhalb über den N. laryngeus inferior.</p><div class="callout merke"><strong>Sicheres Intubationszeichen:</strong> Die Quelle nennt insbesondere den Nachweis von CO₂ in der Exspirationsluft mittels Kapnografie sowie die Intubation unter Sicht.</div>`},
{id:'eFONA',title:'2. Notfall-Landmarken',html:`<p>Für die Koniotomie ist die Membrana cricothyroidea zwischen Schild- und Ringknorpel die Zielstruktur. Das ist keine Detailanatomie: diese Landmarke ist die anatomische Grundlage des Front-of-Neck-Access im nicht oxygenierbaren Atemweg.</p><div class="callout cave"><strong>Prüfungsprinzip:</strong> Atemwegssicherung ist kein Selbstzweck. Das Ziel ist Oxygenierung. Wenn Intubationsversuche die Oxygenierung gefährden, muss die Strategie eskalieren.</div>`},
{id:'alveole',title:'3. Gasaustausch, Totraum und Shuntdenken',html:`<p>Der luftleitende Teil transportiert Gas; der eigentliche Gasaustausch findet in respiratorischen Bronchiolen und Alveolen statt. Pneumozyten Typ I bilden einen großen Teil der dünnen Diffusionsfläche; Typ II produzieren Surfactant und haben Regenerationsfunktion.</p><p><strong>Anatomischer Totraum</strong> bezeichnet ventilierte, aber physiologisch nicht am Gasaustausch beteiligte leitende Atemwege. <strong>Alveolärer Totraum</strong> entsteht, wenn Alveolen belüftet, aber nicht ausreichend perfundiert werden. Das Gegenproblem ist der Shunt: Perfusion ohne ausreichende Ventilation.</p><p>Die hypoxische pulmonale Vasokonstriktion versucht lokal, Blut von schlecht ventilierten Arealen wegzulenken. Dieses Prinzip wird später bei Ein-Lungen-Ventilation wieder wichtig.</p>`},
{id:'mechanik',title:'4. Compliance verstehen statt auswendig lernen',html:`<p><strong>Compliance = ΔV / Δp.</strong> Hohe Compliance bedeutet: eine gegebene Volumenänderung braucht wenig Druck. Niedrige Compliance bedeutet: für dieselbe Volumenänderung wird mehr Druck benötigt.</p><p>Statische Compliance spiegelt vor allem elastische Eigenschaften von Lunge und Thorax wider; die dynamische Compliance wird zusätzlich von Strömungswiderständen beeinflusst. Klinisch hilft dir das, Druckprobleme am Respirator zu zerlegen: Ist die Lunge steifer geworden oder ist der Atemwegswiderstand gestiegen?</p>`},
{id:'oxyvent',title:'5. Oxygenierung ist nicht Ventilation',html:`<p>Diese Trennung ist eine der wichtigsten Grundlagen der Anästhesie.</p><table><thead><tr><th>Frage</th><th>Oxygenierung</th><th>Ventilation</th></tr></thead><tbody><tr><td>Was wird beurteilt?</td><td>O₂-Übertritt ins Blut</td><td>CO₂-Abtransport / alveoläre Ventilation</td></tr><tr><td>Typische Parameter</td><td>PaO₂, SaO₂/SpO₂, PaO₂/FiO₂</td><td>PaCO₂, etCO₂ im Kontext</td></tr><tr><td>Typische Stellschrauben</td><td>FiO₂, PEEP, Rekrutierung/Perfusionsverteilung</td><td>Minutenventilation: Atemzugvolumen × Frequenz</td></tr></tbody></table><div class="callout exam"><strong>Prüfer fragt:</strong> „SpO₂ 99 %, aber PaCO₂ 70 mmHg – wie kann das sein?“<br>Antwort: Eine hohe inspiratorische O₂-Konzentration kann die Oxygenierung erhalten, obwohl die alveoläre Ventilation unzureichend ist. SpO₂ ersetzt keine Ventilationsbeurteilung.</div>`},
{id:'bga',title:'6. BGA in fünf Schritten',html:`<p>Die Quelle teilt die BGA in respiratorischen Status (Oxygenierung und Ventilation) und metabolischen Status (Säure-Basen-Haushalt). Eine robuste Prüfungsmethode ist:</p><ol><li><strong>pH:</strong> Azidämie, Alkalämie oder im Normbereich?</li><li><strong>PaCO₂:</strong> spricht die Richtung für eine respiratorische Komponente?</li><li><strong>HCO₃⁻ / Base Excess:</strong> spricht die Richtung für eine metabolische Komponente?</li><li><strong>Kompensation oder Mischstörung?</strong> Passt die Gegenreaktion qualitativ?</li><li><strong>Kontext:</strong> Laktat, Elektrolyte, Hb, Oxygenierung und klinische Situation.</li></ol><div class="callout merke"><strong>Beispiel aus der Quelle:</strong> Ein hohes Laktat mit negativem Base Excess und niedrigem HCO₃⁻ spricht für eine metabolische Azidose; ein erniedrigtes PaCO₂ kann die respiratorische Kompensation abbilden.</div>${SOURCE_NOTE}`}
],quiz:[
{q:'Welcher Parameter bildet die Ventilation am direktesten ab?',a:['SpO₂','PaCO₂','FiO₂','Hb'],c:1,e:'PaCO₂ ist eng an die alveoläre Ventilation gekoppelt.'},
{q:'Was bedeutet niedrige Compliance?',a:['Wenig Druck erzeugt viel Volumen','Mehr Druck ist für dieselbe Volumenänderung nötig','Der Atemweg ist immer obstruiert','Die Oxygenierung ist automatisch normal'],c:1,e:'Compliance beschreibt Volumenänderung pro Druckänderung.'},
{q:'Welche Struktur ist Ziel einer Koniotomie?',a:['Membrana cricothyroidea','1. Interkostalraum','Ösophagus','Membrana atlantooccipitalis'],c:0,e:'Die Membrana cricothyroidea liegt zwischen Schild- und Ringknorpel.'},
{q:'Was beurteilt eine BGA neben Oxygenierung/Ventilation?',a:['Nur Gerinnung','Säure-Basen-Haushalt','Nur Nierenfunktion','Nur Hb'],c:1,e:'Die BGA liefert auch metabolische Säure-Basen-Informationen.'}]},

cardiophys:{phase:'Phase 1 · Grundlagen',title:'Herz-Kreislauf-Physiologie',intro:'Du sollst Hypotonie nicht mit „mehr Volumen“ beantworten, sondern verstehen, aus welchen physiologischen Komponenten Blutdruck, Herzzeitvolumen und Sauerstoffangebot entstehen.',sources:['Annecke/Hohn · Kap. 1.2.3','Quellenstand 2020'],sections:[
{id:'map',title:'1. Blutdruck als Produkt zweier Größen',html:`<p class="lead">Aus dem Ohm-Gesetz leitet die Quelle für den Kreislauf vereinfacht ab: <strong>Blutdruck ≈ Herzzeitvolumen × systemischer Gefäßwiderstand (SVR)</strong>.</p><p>Das ist ein Denkmodell, kein Ersatz für klinische Messung. Es zwingt dich aber bei Hypotonie zu fragen: Ist das Herzzeitvolumen zu niedrig? Ist der Gefäßwiderstand zu niedrig? Oder beides?</p>`},
{id:'co',title:'2. Herzzeitvolumen zerlegen',html:`<p><strong>HZV = Herzfrequenz × Schlagvolumen.</strong> Das Schlagvolumen wiederum hängt wesentlich von Vorlast, Kontraktilität und Nachlast ab.</p><ul><li><strong>Vorlast:</strong> Füllung des Ventrikels vor der Kontraktion.</li><li><strong>Kontraktilität:</strong> Fähigkeit des Myokards, Kraft zu entwickeln.</li><li><strong>Nachlast:</strong> Widerstand, gegen den der Ventrikel auswerfen muss.</li></ul><div class="callout exam"><strong>Hypotonie nach Einleitung:</strong> Du kannst damit systematisch denken: Vasodilatation → SVR↓; Hypovolämie → Vorlast↓; schwere Pumpstörung → Kontraktilität/HZV↓; mechanische Obstruktion → effektive Nachlast/Ausflussproblem.</div>`},
{id:'starling',title:'3. Frank-Starling und Volumenreagibilität',html:`<p>Im ansteigenden Bereich der Frank-Starling-Kurve kann eine Zunahme der Vorlast das Schlagvolumen steigern. Daraus folgt aber nicht, dass jeder hypotone Patient Volumen braucht.</p><p>Die Quelle beschreibt den Passive-Leg-Raising-Test als reversible Vorlasterhöhung, wenn eine geeignete kontinuierliche HZV-Messung vorliegt. Der klinische Gedanke dahinter ist wichtiger als der Testname: <strong>Volumen geben, wenn Volumenreagibilität plausibel ist, und die Wirkung messen.</strong></p>`},
{id:'oxygen',title:'4. Sauerstoffangebot ist mehr als SpO₂',html:`<p>Der arterielle Sauerstoffgehalt wird überwiegend durch Hämoglobinkonzentration und Hämoglobinsättigung bestimmt; der physikalisch gelöste Anteil ist im Normalbereich klein. Das Sauerstoffangebot an das Gewebe ergibt sich konzeptionell aus <strong>Herzzeitvolumen × arteriellem O₂-Gehalt</strong>.</p><p>Damit wird klar, warum ein Patient trotz SpO₂ 100 % eine kritische Sauerstoffversorgung haben kann: z. B. bei schwerer Anämie oder sehr niedrigem Herzzeitvolumen.</p>`},
{id:'perfusion',title:'5. Perfusion erkennen',html:`<p>Bei unzureichender Gewebedurchblutung steigt die Sauerstoffausschöpfung. Laktat kann bei anaerobem Stoffwechsel ansteigen. Die Quelle nutzt zentral-/gemischtvenöse Sättigung und Laktat als Hinweise im Gesamtkontext.</p><div class="callout merke"><strong>Prüfungsregel:</strong> Behandle nicht „den Blutdruck“. Behandle die Pathophysiologie und prüfe anschließend, ob Organperfusion und Kreislauf tatsächlich besser werden.</div>${SOURCE_NOTE}`}
],quiz:[
{q:'Woraus besteht das Herzzeitvolumen?',a:['MAP × SVR','HF × Schlagvolumen','Hb × SpO₂','PEEP × VT'],c:1,e:'HZV = HF × SV.'},
{q:'Welche Größe gehört NICHT zu den Hauptdeterminanten des Schlagvolumens?',a:['Vorlast','Kontraktilität','Nachlast','FiO₂'],c:3,e:'FiO₂ ist keine primäre Determinante des Schlagvolumens.'},
{q:'Warum kann SpO₂ 100 % trotz kritischer O₂-Versorgung vorkommen?',a:['Weil Hb und Herzzeitvolumen ebenfalls das O₂-Angebot bestimmen','Weil SpO₂ immer falsch ist','Weil PaCO₂ gleich Hb ist','Das ist unmöglich'],c:0,e:'O₂-Angebot hängt vom O₂-Gehalt und Herzzeitvolumen ab.'}]},

renal:{phase:'Phase 1 · Grundlagen',title:'Nierenphysiologie & perioperative Relevanz',intro:'Niere bedeutet in der Prüfung mehr als Kreatinin: Perfusion, Wasser, Elektrolyte, Säure-Basen-Haushalt, Medikamentenelimination und Dialyseplanung hängen zusammen.',sources:['Annecke/Hohn · Kap. 1.2.4','Quellenstand 2020'],sections:[
{id:'function',title:'1. Was die Niere für die Anästhesie leistet',html:`<p class="lead">Die Quelle ordnet der Niere vier große Aufgaben zu: <strong>Wasser-/Elektrolythomöostase, Exkretion hydrophiler Stoffe, endokrine Funktionen und Blutdruckregulation.</strong></p><p>Die Niere erhält einen großen Anteil des Herzzeitvolumens. Deshalb reagiert sie empfindlich auf Kreislaufstörungen und ist ein wichtiges Zielorgan bei Schock.</p>`},
{id:'gfr',title:'2. GFR – was bedeutet das?',html:`<p>Im Glomerulum entsteht Primärharn; im Tubulussystem wird der überwiegende Anteil rückresorbiert und es findet zusätzliche Sekretion statt. Die <strong>glomeruläre Filtrationsrate (GFR)</strong> beschreibt das pro Zeit von allen Glomeruli gebildete Filtrat und ist ein zentraler Funktionsparameter.</p><p>Serumkreatinin wird zur Abschätzung der GFR verwendet, ist aber von individuellen Faktoren wie Muskelmasse beeinflusst. In der Prüfung solltest du deshalb nicht „Kreatinin = Niere“ sagen, sondern GFR, Diurese, Verlauf und klinischen Kontext zusammen denken.</p>`},
{id:'aki',title:'3. Akut oder chronisch?',html:`<p>Akute Nierenschädigung entsteht häufig im Kontext von Hypovolämie, Hypotonie oder Schock, kann aber auch intrinsische oder postrenale Ursachen haben. Chronische Niereninsuffizienz entwickelt sich über längere Zeit durch Nephronverlust, etwa bei Diabetes oder Hypertonie.</p><div class="callout exam"><strong>Prüfer fragt:</strong> „Postoperativ plötzlich Oligurie – was tun Sie?“<br>Antwortstruktur: Messung/Abfluss prüfen → Kreislauf und Volumenstatus → prärenal/intrarenal/postrenal differenzieren → Elektrolyte und Säure-Basen-Status → nephrotoxische Faktoren/Medikamente → Verlauf und ggf. Nierenersatzverfahren.</div>`},
{id:'esrd',title:'4. Dialysepatient vor Anästhesie',html:`<p>Im Buch werden bei terminaler Niereninsuffizienz besonders Restausscheidung, Dialysefrequenz, Medikation, Retentionsparameter, Elektrolyte und Hämoglobin hervorgehoben. Klinisch wichtig sind außerdem Überwässerung/Herzinsuffizienzzeichen und der Dialysezugang.</p><p>Vor Einleitung sind insbesondere Kalium, pH und Hb wichtige Größen. Bei der Medikamentenwahl muss die Organabhängigkeit von Elimination und aktiven Metaboliten berücksichtigt werden.</p><div class="callout cave"><strong>Quellenalter:</strong> Konkrete Dialysezeitpunkte und Medikamentenempfehlungen werden vor Veröffentlichung als 2026-Standard separat leitliniengeprüft.</div>${SOURCE_NOTE}`}
],quiz:[
{q:'Was beschreibt die GFR?',a:['Ausschließlich die Urinmenge pro Tag','Das Filtratvolumen der Glomeruli pro Zeiteinheit','Die Kaliumkonzentration','Den renalen Blutdruck'],c:1,e:'Die GFR ist ein Filtrationsparameter.'},
{q:'Welche Dreiteilung hilft bei akuter Oligurie?',a:['Prärenal – intrarenal – postrenal','Links – rechts – zentral','Systolisch – diastolisch – gemischt','Hypoxisch – hyperoxisch – normal'],c:0,e:'Die Ursachen werden klassisch prärenal, intrarenal und postrenal strukturiert.'},
{q:'Welche Werte sind bei Dialysepatienten vor Einleitung besonders relevant?',a:['Nur INR','Kalium, pH und Hb im Kontext','Nur TSH','Nur Bilirubin'],c:1,e:'Elektrolyte, Säure-Basen-Status und Hb sind zentrale Sicherheitsgrößen.'}]},

livergi:{phase:'Phase 1 · Grundlagen',title:'Leber & Gastrointestinaltrakt',intro:'Die Leber verbindet Pharmakologie, Gerinnung, Kreislauf und Stoffwechsel. Der Gastrointestinaltrakt führt dich direkt zum Aspirationsrisiko.',sources:['Annecke/Hohn · Kap. 1.2.5','Quellenstand 2020'],sections:[
{id:'blood',title:'1. Die doppelte Blutversorgung der Leber',html:`<p class="lead">Die Leber erhält Blut aus <strong>V. portae</strong> und <strong>A. hepatica</strong>. In der Quelle stammen ungefähr zwei Drittel des Leberblutflusses aus der Pfortader; die arterielle Versorgung trägt einen wesentlichen Anteil zur O₂-Versorgung bei.</p><p>Die arterielle Durchblutung kann Änderungen der portalen Perfusion teilweise kompensieren. Für die Anästhesie folgt daraus: ausgeprägte Hypotonie, venöse Stauung und ungünstige Beatmungs-/Kreislaufbedingungen können die hepatische Perfusion beeinträchtigen.</p>`},
{id:'functions',title:'2. Vier Funktionen, die du klinisch brauchst',html:`<ul><li><strong>Synthese:</strong> Albumin, Gerinnungsfaktoren, Pseudocholinesterase, Stoffwechselprodukte.</li><li><strong>Metabolismus:</strong> unter anderem Biotransformation vieler Medikamente.</li><li><strong>Entgiftung:</strong> Verarbeitung endogener und exogener Substanzen.</li><li><strong>Exkretion:</strong> z. B. Bilirubin und bestimmte Arzneistoffe/Metaboliten.</li></ul><p>Wenn diese Funktionen ausfallen, entstehen nicht nur „schlechte Leberwerte“, sondern konkrete anästhesiologische Konsequenzen: veränderte Medikamentenwirkung, Gerinnungsprobleme, Enzephalopathie, Volumenverteilungsstörungen und erhöhtes perioperatives Risiko.</p>`},
{id:'cirrhosis',title:'3. Zirrhose – systemische Erkrankung',html:`<p>Die Quelle beschreibt Zirrhose als narbig-fibrotischen Umbau mit Verlust von Synthese- und Entgiftungsfunktion. Klinische Manifestationen können Ikterus, Aszites, portale Hypertension, Blutungsneigung und hepatische Enzephalopathie umfassen.</p><p>Für deine Anästhesieplanung prüfst du daher nicht nur Transaminasen: Kreislauf, Nierenfunktion, Gerinnung, Ernährung, Enzephalopathie, Aszites/Aspiration und Medikamentenkinetik gehören zusammen.</p>`},
{id:'drugs',title:'4. Warum Medikamente länger wirken können',html:`<p>Bei schwerer Leberfunktionsstörung kann die Metabolisierung verschiedener Anästhetika und Opioide reduziert sein. Zusätzlich kann eine verminderte Synthese der Plasmacholinesterase die Wirkdauer von Substanzen beeinflussen, die über dieses Enzym abgebaut werden.</p><div class="callout merke"><strong>Prüfungsantwort:</strong> „Ich wähle nicht pauschal ein anderes Narkosemittel, sondern prüfe Organabhängigkeit von Metabolismus/Elimination, Proteinbindung, aktive Metaboliten und die klinische Schwere der Lebererkrankung.“</div>`},
{id:'gi',title:'5. Ösophagus, Magen und Aspiration',html:`<p>Der Ösophagus transportiert Nahrung und bildet zusammen mit seinen Sphinkteren eine Barriere gegen Reflux. Der untere Sphinkter trennt den Magen vom Ösophagus; Störungen der Magenentleerung, Reflux oder mechanische Passageprobleme können das Aspirationsrisiko erhöhen.</p><p>Damit ist diese Physiologie die Grundlage für spätere Fragen zu Nüchternheit, Ileus, RSI und Aspiration.</p>${SOURCE_NOTE}`}
],quiz:[
{q:'Welche beiden Gefäße versorgen die Leber?',a:['V. portae und A. hepatica','Aorta und V. jugularis','A. pulmonalis und V. cava superior','Nur A. hepatica'],c:0,e:'Die Leber besitzt eine duale Blutversorgung.'},
{q:'Warum kann Leberinsuffizienz die Wirkdauer von Medikamenten verlängern?',a:['Nur wegen Hypoxämie','Durch veränderten Metabolismus/Synthese und je nach Substanz Elimination','Weil alle Medikamente renal eliminiert werden','Sie hat keinen Einfluss'],c:1,e:'Die Leber ist zentrales Stoffwechsel- und Syntheseorgan.'},
{q:'Welche Themen gehören bei Zirrhose zusammen?',a:['Nur Transaminasen','Gerinnung, Niere, Kreislauf, Enzephalopathie und Pharmakokinetik','Nur Atemweg','Nur Hautfarbe'],c:1,e:'Zirrhose ist perioperativ eine systemische Erkrankung.'}]},

endocrine:{phase:'Phase 1 · Grundlagen',title:'Endokrinologie: Schilddrüse, Diabetes & Stressachse',intro:'Du lernst endokrine Erkrankungen über ihre perioperativen Konsequenzen: Kreislauf, Stoffwechsel, Elektrolyte, Atemweg und Stressantwort.',sources:['Annecke/Hohn · Kap. 1.2.6 + Kap. 2.1.5','Quellenstand 2020'],sections:[
{id:'thyroid',title:'1. Schilddrüse als Stoffwechselregler',html:`<p class="lead">Die Schilddrüse bildet die jodhaltigen Hormone T4 und T3; ihre Synthese wird über TSH stimuliert. Diese Hormone beeinflussen den Gesamtmetabolismus und damit auch Kreislaufreaktionen.</p><p>Bei einer vergrößerten Schilddrüse kommt ein zweites anästhesiologisches Problem hinzu: Verlagerung oder Einengung der Trachea kann das Airway-Management erschweren.</p>`},
{id:'hyper',title:'2. Hyperthyreose',html:`<p>In der Quelle stehen kardiale Folgen im Vordergrund: Tachykardie, Vorhofflimmern, erhöhtes Herzzeitvolumen und erniedrigter peripherer Widerstand. Für elektive Eingriffe wird ein euthyreoter Zustand angestrebt.</p><p>Prüfungslogik: erkenne die Kombination aus hypermetabolem Zustand und kardialer Belastung. Bei akuter Tachykardie/Hyperthermie intraoperativ gehören neben anderen Ursachen auch thyreotoxische Krise und maligne Hyperthermie in die Differenzialdiagnose.</p>`},
{id:'hypo',title:'3. Hypothyreose',html:`<p>Die Quelle nennt u. a. Bradykardie, Antriebsschwäche, gestörte Thermoregulation und Elektrolytveränderungen. Besonders relevant sind eine reduzierte Kreislaufreserve, verminderte ventilatorische Antwort und potenziell verzögerter Medikamentenabbau mit langsamem Erwachen.</p><div class="callout cave"><strong>Nicht verwechseln:</strong> Die Diagnose und Therapie einer manifesten Schilddrüsenerkrankung ist nicht allein aus einem Narkosemonitor abzuleiten. Die Prüfungsfrage zielt auf Erkennung der Konsequenzen und sichere Planung.</div>`},
{id:'diabetes',title:'4. Diabetes mellitus – warum er perioperativ wichtig ist',html:`<p>Typ-1-Diabetes bedeutet absoluten Insulinmangel; ohne externe Insulinzufuhr droht Ketoazidose. Bei Typ 2 stehen Insulinresistenz und/oder relative Sekretionsstörung im Vordergrund.</p><p>Das perioperative Risiko entsteht nicht nur durch den Glukosewert. Langzeitfolgen betreffen Herz/Kreislauf, Niere, Wundheilung und autonome Nerven. Eine autonome Neuropathie kann zum Beispiel Magenentleerung und Kreislaufregulation beeinflussen.</p><div class="callout merke"><strong>Prüfungsstruktur bei Diabetes:</strong> Typ klären → Therapie/Insulinabhängigkeit → Endorganschäden → aktuelle Glukose → Elektrolyte/Säure-Basen → Aspirations- und Kreislaufrisiko → engmaschige perioperative Kontrolle.</div>`},
{id:'adrenal',title:'5. Nebennierenrinde und chronische Steroidtherapie',html:`<p>Eine längerfristige systemische Glukokortikoidtherapie kann die körpereigene Stressantwort supprimieren. Die Quelle beschreibt als Risiko eine relative oder manifeste Nebennierenrindeninsuffizienz mit Hypotonie, Hypovolämie, Hypoglykämie und Elektrolytstörungen.</p><p>Für die Prüfung ist das Prinzip entscheidend: <strong>Patienten unter relevanter chronischer Steroidexposition können auf den Operationsstress nicht normal mit einer Kortisolsteigerung reagieren.</strong> Konkrete perioperative Substitutionsschemata werden im aktuellen Leitlinienabgleich separat gepflegt.</p>${SOURCE_NOTE}`}
],quiz:[
{q:'Welche kardiale Veränderung passt zur Hyperthyreose?',a:['Ausgeprägte Bradykardie als Leitsymptom','Tachykardie und mögliches Vorhofflimmern','Immer niedrige Herzzeitvolumina','Keine Kreislaufwirkung'],c:1,e:'Die Quelle betont die kardiale Hyperaktivität.'},
{q:'Warum ist Typ-1-Diabetes perioperativ besonders relevant?',a:['Insulin ist nie erforderlich','Absoluter Insulinmangel kann ohne Zufuhr zur Ketoazidose führen','Nur wegen HbA1c','Weil keine Endorganschäden auftreten'],c:1,e:'Bei Typ 1 muss eine ausreichende Insulinversorgung gewährleistet bleiben.'},
{q:'Was kann chronische Glukokortikoidtherapie beeinträchtigen?',a:['Nur die Pupillenweite','Die endogene Stress-Kortisolantwort','Nur SpO₂','Nur den Zahnstatus'],c:1,e:'Suppression der HPA-Achse kann die Stressantwort vermindern.'}]},

hypnotics:{phase:'Phase 2 · Pharmakologie & Technik',title:'Hypnotika – wirklich verstehen',intro:'Nicht „Propofol = Hypnotikum“ auswendig lernen. Du verstehst die fünf klassischen i.v. Induktionshypnotika, ihre Rezeptoren, Hämodynamik, Pharmakokinetik, Nebenwirkungen und die patientenbezogene Auswahl.',sources:['Annecke/Hohn · Kap. 1.3.1','Springer Facharzt-Training Heft 1 · Fall 7','Quellenstand 2019/2020'],sections:[
{id:'concept',title:'1. Was macht ein Hypnotikum?',html:`<p class="lead">Ein Hypnotikum erzeugt dosisabhängig Sedierung bis hin zur Hypnose. Das ist nicht dasselbe wie Analgesie. Genau diese Trennung ist wichtig, weil eine Allgemeinanästhesie meist aus mehreren Komponenten besteht: Hypnose, Analgesie und – falls erforderlich – neuromuskuläre Blockade.</p><p>Die beiden bereitgestellten Quellen behandeln fünf klassische i.v. Induktionshypnotika: <strong>Propofol, Thiopental, Etomidat, Ketamin und Midazolam.</strong></p><table><thead><tr><th>Substanz</th><th>Stoffgruppe</th><th>Dominante Prüfungsassoziation</th></tr></thead><tbody><tr><td>Propofol</td><td>substituiertes Phenol</td><td>schnell steuerbar, antiemetisch, aber ausgeprägte Kreislauf-/Atemdepression möglich</td></tr><tr><td>Thiopental</td><td>Thiobarbiturat</td><td>schneller Wirkungseintritt, myokardiale Depression; Porphyrieproblem</td></tr><tr><td>Etomidat</td><td>Imidazolderivat</td><td>hämodynamisch stabiler, aber Nebennierenrindensuppression</td></tr><tr><td>Ketamin</td><td>Phencyclidin-/Arylcycloalkylamin-Derivat</td><td>NMDA, Analgesie, sympathische Stimulation, dissoziative Anästhesie</td></tr><tr><td>Midazolam</td><td>Benzodiazepin</td><td>GABA-A, Sedierung/Amnesie; als alleinige schnelle Induktion weniger steuerbar</td></tr></tbody></table>`},
{id:'ideal',title:'2. Das ideale Induktionshypnotikum',html:`<p>Das Sonderheft nutzt eine sehr gute Denkübung: Statt Präparate einzeln zu memorieren, stell dir zuerst das ideale Medikament vor. Es sollte schnell wirken, gut steuerbar enden, kardiorespiratorisch stabil sein, keine Organperfusion verschlechtern, möglichst organunabhängig eliminiert werden, nicht kumulieren, keine Schmerzen bei Injektion verursachen und eine große Sicherheitsbreite haben.</p><p>Keines der realen Medikamente erfüllt alles. <strong>Die Wahl ist deshalb immer ein Kompromiss zwischen Patient, Operation und Nebenwirkungsprofil.</strong></p><div class="callout exam"><strong>Prüfer fragt nicht nur:</strong> „Welche Dosis Propofol?“<br>Er kann fragen: „Warum ist Propofol bei diesem Patienten die schlechtere Wahl? Was gewinnen und was verlieren Sie mit Etomidat oder Ketamin?“</div>`},
{id:'receptors',title:'3. Rezeptoren: warum Ketamin anders ist',html:`<p>Propofol, Thiopental, Etomidat und Benzodiazepine verstärken in den Quellen die inhibitorische GABA-A-vermittelte Signalübertragung. Der GABA-A-Rezeptor ist ein ligandengesteuerter Chloridkanal; vermehrter Chlorideinstrom hyperpolarisiert die Zellmembran und hemmt neuronale Signalübertragung.</p><p><strong>Ketamin</strong> unterscheidet sich: seine zentrale Prüfungswirkung läuft über den <strong>NMDA-Rezeptor</strong>. Damit erklärt sich auch, warum Ketamin gleichzeitig eine ausgeprägte analgetische Komponente besitzt und eine dissoziative Anästhesie erzeugt.</p>`},
{id:'pk',title:'4. Warum eine kurze Boluswirkung nicht gleich schnelle Elimination bedeutet',html:`<p>Nach einer i.v. Bolusgabe verteilt sich ein lipophiles Hypnotikum zunächst rasch in gut perfundierte Organe, insbesondere das Gehirn. Das Ende der Hypnose nach einem einzelnen Bolus beruht oft zunächst auf <strong>Umverteilung</strong>, nicht darauf, dass das Medikament schon vollständig eliminiert wurde.</p><p>Bei längerer Infusion werden periphere Kompartimente zunehmend gefüllt. Deshalb ist die <strong>kontextsensitive Halbwertszeit</strong> für die Steuerbarkeit nach Infusion klinisch wichtiger als eine einfache Eliminationshalbwertszeit.</p><div class="callout merke"><strong>Prüfungssatz:</strong> „Boluswirkung endet häufig durch Redistribution; bei Infusion entscheidet die zeitabhängige Gewebesättigung mit über das Erwachen.“</div>`},
{id:'propofol',title:'5. Propofol im Detail',html:`<p><strong>Pharmakologie:</strong> Propofol ist 2,6-Diisopropylphenol und wegen seiner Wasserunlöslichkeit als Lipidemulsion formuliert. Die Quelle nennt Injektionsschmerz und Kontaminationsrisiko als praktische Punkte.</p><p><strong>ZNS:</strong> dosisabhängige Senkung des zerebralen Sauerstoffverbrauchs und der Hirndurchblutung; dadurch kann auch der ICP sinken. Hohe Dosen können ein Burst-Suppression-Muster im EEG erzeugen.</p><p><strong>Atmung:</strong> gute Dämpfung laryngealer Reflexe, aber dosisabhängige Atemdepression.</p><p><strong>Kreislauf:</strong> negativ inotrop, Sympathikolyse und periphere Vasodilatation; zusätzlich kann Bradykardie durch gedämpften Baroreflex auftreten. Deshalb müssen ältere, hypovoläme oder kritisch kranke Patienten deutlich vorsichtiger titriert werden.</p><p><strong>Weitere Punkte:</strong> keine relevante Analgesie; PONV tritt unter Propofol seltener auf; die Boluswirkung endet wesentlich durch Umverteilung. Metabolismus erfolgt überwiegend durch Konjugation mit anschließender renaler Elimination, zusätzlich ist extrahepatischer Metabolismus beschrieben.</p><div class="callout cave"><strong>Dosis:</strong> Die hochgeladenen Kapitel nennen im direkten Vergleich 2 mg/kg als Erwachsenen-Beispieldosis, zeigen aber gerade daran einen deutlichen Blutdruckabfall. Das ist hier <b>kein pauschales Dosierungsrezept</b>. In der Prüfung ist die patienten- und kreislaufadaptierte Titration wichtiger als eine starre Zahl.</div>`},
{id:'pris',title:'6. PRIS – die seltene, aber klassische Propofolfrage',html:`<p>Das Propofol-Infusionssyndrom wird in Annecke/Hohn als potenziell lebensbedrohliches Syndrom beschrieben. Typische Komponenten sind <strong>Schock, schwere metabolische Azidose, Arrhythmien, Rhabdomyolyse, Nierenversagen und Hypertriglyzeridämie.</strong></p><p>Als Risikokontext nennt die Quelle schwere Grunderkrankung, Polytrauma, SHT, mitochondriale Erkrankungen sowie längere und/oder hoch dosierte Propofolgabe. Bei Verdacht ist die Propofolzufuhr zu beenden und intensivmedizinisch supportiv zu behandeln.</p><div class="callout exam"><strong>Prüferfrage:</strong> „Patient auf Intensivstation unter Propofol entwickelt unerklärte Azidose, Kreislaufinstabilität und CK-Anstieg. Woran denken Sie?“ → PRIS aktiv nennen.</div>`},
{id:'etomidate',title:'7. Etomidat',html:`<p>Etomidat ist ein Imidazolderivat. Sein großer Vorteil in den Quellen ist die <strong>vergleichsweise hohe hämodynamische Stabilität</strong>: Herzzeitvolumen und Kontraktilität bleiben eher erhalten und der mittlere arterielle Druck wird weniger beeinflusst als durch andere klassische Induktionshypnotika.</p><p>Der entscheidende Nachteil ist die <strong>Suppression der Nebennierenrindenfunktion</strong>. Bereits eine Einleitungsdosis kann Kortisol-/Aldosteronspiegel und die ACTH-Antwort beeinflussen. Deshalb diskutieren die historischen Quellen seinen Einsatz besonders kritisch bei Sepsis und in der Intensivmedizin.</p><div class="callout cave"><strong>Wichtig:</strong> Das ist die Darstellung der 2019/2020-Quellen. Die genaue heutige Rolle von Etomidat wird im Leitlinienabgleich gesondert aktualisiert.</div>`},
{id:'ketamine',title:'8. Ketamin / S-Ketamin',html:`<p>Ketamin ist ein Phencyclidinderivat und wirkt vor allem am NMDA-Rezeptor. Im Gegensatz zu den anderen klassischen Induktionshypnotika besitzt es eine <strong>ausgeprägte Analgesie</strong> und führt typischerweise zu sympathischer Kreislaufstimulation.</p><p>Deshalb wird es in den Quellen besonders bei hypovolämischen oder septischen Schockzuständen diskutiert. Aber „Ketamin = immer kreislaufstabil“ wäre zu einfach: Bei kardialen Hochrisikopatienten kann die Steigerung von Herzfrequenz, Herzzeitvolumen und myokardialem O₂-Verbrauch problematisch sein.</p><p>Ketamin erzeugt eine dissoziative Anästhesie; unangenehme Träume und Halluzinationen werden beschrieben. Die Quelle kombiniert es deshalb häufig mit einem Benzodiazepin beziehungsweise kleiner Propofolgabe.</p><table><thead><tr><th>In der Quelle angegebene Dosis (2020)</th><th>Angabe</th></tr></thead><tbody><tr><td>Ketamin i.v. zur Einleitung</td><td>1–2 mg/kg</td></tr><tr><td>Ketamin i.v. zur Notfallanalgesie</td><td>0,2–0,5 mg/kg</td></tr><tr><td>S-Ketamin</td><td>etwa Hälfte der Ketamindosis</td></tr></tbody></table><div class="callout source"><strong>Diese Zahlen sind Quellenwerte von 2020.</strong> Vor klinischer Verwendung immer aktuelle Fachinformation und lokale SOP prüfen.</div>`},
{id:'thiopental',title:'9. Thiopental',html:`<p>Thiopental ist ein Thiobarbiturat. Es wirkt ebenfalls über GABA-A-vermittelte Hemmung. Hämodynamisch beschreibt das Sonderheft direkte myokardiale Dämpfung, Abnahme des Herzzeitvolumens und eine vorlastsenkende Vasodilatation; der Baroreflex bleibt im Vergleich zu Propofol eher erhalten, sodass die Herzfrequenz moderat steigen kann.</p><p>Ein klassischer Prüfpunkt ist die <strong>akute intermittierende Porphyrie</strong>: Barbiturate sind dort in der Buchkasuistik kontraindiziert.</p><p>Im Trauma-Fall des Sonderhefts wird außerdem diskutiert, dass Azidose den Anteil der pharmakologisch aktiven freien Thiopentalsäure verändern kann. Das ist ein Beispiel dafür, warum im Schock eine normale „Standarddosis“ nicht einfach übertragen werden darf.</p>`},
{id:'midazolam',title:'10. Midazolam',html:`<p>Midazolam ist ein Benzodiazepin und wirkt GABA-A-vermittelt. Es bietet Sedierung und Amnesie, ist aber als alleinige Substanz für eine schnell steuerbare Narkoseeinleitung nicht in jeder Situation ideal.</p><p>Ein wichtiger klinischer Lernpunkt aus dem Sonderheft: Auch Medikamente, die im gesunden Patienten als relativ kreislaufschonend gelten, können im ausgeprägten Schock nach Verlust der endogenen Katecholaminstütze eine relevante Hypotonie auslösen. „Kreislaufneutral“ ist also immer kontextabhängig.</p>`},
{id:'compare',title:'11. Die Auswahl am Patienten – Vergleichsmatrix',html:`<div class="compare"><table><thead><tr><th>Situation</th><th>Was du abwägst</th><th>Prüfungslogik</th></tr></thead><tbody><tr><td>Gesunder elektiver Patient</td><td>Steuerbarkeit, PONV, Kreislauf, Atemweg</td><td>Propofol ist häufig naheliegend, aber Dosis an Patient anpassen.</td></tr><tr><td>Schwere Hypovolämie / Schock</td><td>Verlust von Sympathikotonus und Vorlast</td><td>Stark kreislaufdepressive Induktion vermeiden; Ketamin wird in den Quellen als Option diskutiert.</td></tr><tr><td>Sepsis</td><td>Kreislauf + Nebennierenfunktion</td><td>Etomidat-Vorteil der Hämodynamik gegen NNR-Suppression abwägen; Quellenstand beachten.</td></tr><tr><td>Akute intermittierende Porphyrie</td><td>Porphyrinogenität</td><td>Barbiturate vermeiden; Quelle wählt Propofol zur Einleitung.</td></tr><tr><td>SHT</td><td>CPP, Blutdruck, Ventilation, O₂-Bedarf</td><td>Nicht ein Medikament isoliert, sondern sekundäre Hirnschädigung vermeiden.</td></tr></tbody></table></div><div class="callout merke"><strong>Goldener Satz:</strong> „Ich wähle das Hypnotikum nicht nach Gewohnheit, sondern nach Kreislaufreserve, Atemweg, Organfunktion, Begleiterkrankung, gewünschter Steuerbarkeit und substanzspezifischen Nebenwirkungen.“</div>`},
{id:'case',title:'12. Facharztfall: Trauma + SHT + Hypotonie',html:`<p>Das Springer-Sonderheft nutzt einen älteren polytraumatisierten Patienten mit intrakranieller Blutung, Femurfrakturen, Tachykardie und Hypotonie als Ausgangspunkt.</p><p><strong>So bearbeitest du den Fall:</strong></p><ol><li>Erkenne Blutverlust/Hypovolämie und SHT als konkurrierende Risiken.</li><li>Definiere dein Ziel: schnelle sichere Atemwegssicherung ohne zusätzlichen Kreislaufkollaps und ohne sekundäre zerebrale Schädigung.</li><li>Bereite Kreislaufunterstützung und Monitoring vor, statt nur das „richtige Hypnotikum“ zu suchen.</li><li>Titriere die Induktionsmedikation an die reduzierte Kreislaufreserve.</li><li>Begründe deine Wahl über Pharmakodynamik und nicht über Gewohnheit.</li></ol><div class="callout exam"><strong>Prüfer-Nachfragen:</strong> Welche fünf klassischen i.v. Hypnotika? Welche Rezeptoren? Wie unterscheiden sich Propofol, Thiopental und Etomidat hämodynamisch? Welche substanzspezifischen Risiken? Welches Präparat in diesem konkreten Schockzustand und warum?</div>${SOURCE_NOTE}`}
],quiz:[
{q:'Welches der fünf klassischen Induktionshypnotika wirkt primär über NMDA-Antagonismus?',a:['Propofol','Etomidat','Ketamin','Midazolam'],c:2,e:'Ketamin ist der zentrale NMDA-Vertreter in den Quellen.'},
{q:'Welche Aussage zu Propofol passt?',a:['Es besitzt ausgeprägte Analgesie','Es kann Vasodilatation, negative Inotropie und Bradykardie verursachen','Es stimuliert immer den Sympathikus','Es hat keine Atemwirkung'],c:1,e:'Propofol kann Kreislauf und Atmung dosisabhängig deutlich depressiv beeinflussen.'},
{q:'Was ist der klassische Nachteil von Etomidat?',a:['Ausgeprägte Histaminfreisetzung','Nebennierenrindensuppression','Maligne Hyperthermie als Hauptproblem','Starke Analgesie'],c:1,e:'Die NNR-Suppression ist der klassische Prüfpunkt.'},
{q:'Welche Eigenschaft unterscheidet Ketamin besonders?',a:['Keine Analgesie','Ausgeprägte Analgesie und dissoziative Anästhesie','Nur periphere Wirkung','Irreversible Muskelrelaxation'],c:1,e:'Ketamin kombiniert Hypnose mit relevanter Analgesie und dissoziativer Anästhesie.'},
{q:'Warum endet die Wirkung eines i.v. Bolus häufig rasch?',a:['Das Medikament ist sofort vollständig ausgeschieden','Redistribution aus dem Gehirn in andere Kompartimente','Nur wegen Nierenfiltration','Weil der Rezeptor zerstört wird'],c:1,e:'Bei vielen lipophilen Hypnotika beendet zunächst Umverteilung die zentrale Wirkung.'},
{q:'Welche Konstellation passt zu PRIS?',a:['Metabolische Azidose, Schock, Rhabdomyolyse/Arrhythmien','Nur Obstipation','Isolierte Miosis','Hyperthyreose'],c:0,e:'Das sind typische in der Quelle genannte Komponenten.'}]}
};

const $=s=>document.querySelector(s);let current=null;let answers={};
function esc(t=''){return String(t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function requested(){return new URLSearchParams(location.search).get('lesson')||'exam'}
function courseState(){return JSON.parse(localStorage.getItem('aft_course')||'{}')}
function setCourseState(x){localStorage.setItem('aft_course',JSON.stringify({...courseState(),...x}))}
function mainProgress(){const s=JSON.parse(localStorage.getItem('aft100')||'{"done":[]}');return s.done||[]}
function isCompleted(id){return mainProgress().includes(id)}
function render(){const id=requested();current=COURSES[id];if(!current){renderPending(id);return}document.title=current.title+' · Anästhesie Facharzt Trainer';$('#coursePhase').textContent=current.phase;$('#courseTitle').textContent=current.title;$('#courseIntro').textContent=current.intro;$('#courseTags').innerHTML=current.sources.map(x=>`<span class="tag">${esc(x)}</span>`).join('');$('#courseStatus').textContent=isCompleted(id)?'✓ Im 0→100-Pfad abgeschlossen':'Vollkurs · noch nicht abgeschlossen';$('#courseContent').innerHTML=current.sections.map((s,i)=>`<section class="section" id="${s.id}" data-section="${s.id}"><div class="eyebrow">KAPITEL ${i+1}/${current.sections.length}</div><h2>${s.title}</h2>${s.html}</section>`).join('');$('#toc').innerHTML=current.sections.map((s,i)=>`<button onclick="goSection('${s.id}')">${i+1}. ${s.title.replace(/^\d+\.\s*/, '')}</button>`).join('')+`<button onclick="goSection('quizSection')">✓ Selbsttest</button>`;renderQuiz();$('#quizSection').style.display='block';$('#finish').style.display='flex';$('#completeBtn').textContent=isCompleted(id)?'✓ Bereits abgeschlossen':'✓ Lektion abschließen';setupObserver();updateRead();updateNav()}
function renderPending(id){const title=id.replace(/[-_]/g,' ');$('#coursePhase').textContent='KURS IM AUFBAU';$('#courseTitle').textContent=title.charAt(0).toUpperCase()+title.slice(1);$('#courseIntro').textContent='Diese Einheit ist im 0→100-Fahrplan angelegt, aber der vollständige Quellenkurs ist noch nicht freigegeben.';$('#courseTags').innerHTML='<span class="tag">Nicht als gelernt markieren</span>';$('#toc').innerHTML='';$('#courseContent').innerHTML=`<div class="empty"><h2>Dieser Vollkurs wird noch aufgebaut.</h2><p>Ich zeige hier absichtlich keine dünne Stichwortliste mehr. Erst wenn die Lerneinheit als echter Kurs mit Erklärung, Prüfungsfragen und Quellenabgleich vorliegt, wird sie freigegeben.</p><a class="btn primary" href="lernplan.html">← Zum 0→100 Lernpfad</a></div>`;$('#quizSection').style.display='none';$('#finish').style.display='none';updateNav()}
function renderQuiz(){answers={};$('#quiz').innerHTML=current.quiz.map((q,qi)=>`<div class="qcard" id="q-${qi}"><strong>${qi+1}. ${q.q}</strong><div class="answers">${q.a.map((a,ai)=>`<button class="answer" onclick="answer(${qi},${ai},this)">${esc(a)}</button>`).join('')}</div><div class="feedback" id="fb-${qi}"></div></div>`).join('')}
function answer(qi,ai,btn){if(answers[qi]!=null)return;answers[qi]=ai;const q=current.quiz[qi],box=$('#q-'+qi),buttons=[...box.querySelectorAll('.answer')];buttons.forEach((b,i)=>{b.disabled=true;if(i===q.c)b.classList.add('good');if(i===ai&&i!==q.c)b.classList.add('bad')});$('#fb-'+qi).innerHTML=`<strong>${ai===q.c?'Richtig.':'Nicht ganz.'}</strong> ${q.e}`;updateRead()}
function updateRead(){if(!current)return;const seen=(courseState()[requested()]||{}).seen||[];const quizDone=Object.keys(answers).length;const total=current.sections.length+current.quiz.length;const value=Math.round((Math.min(current.sections.length,seen.length)+quizDone)/total*100);$('#readPct').textContent=value+'%';$('#readBar').style.width=value+'%';if(value===100)$('#finishText').textContent='Alle Abschnitte wurden besucht und alle Quizfragen beantwortet. Wenn du die Kernaussagen frei erklären kannst, schließe die Lektion ab.'}
function goSection(id){const el=document.getElementById(id);if(el)el.scrollIntoView({behavior:'smooth',block:'start'})}
function setupObserver(){const obs=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){const id=requested(),st=courseState(),cs=st[id]||{seen:[]};if(!cs.seen.includes(e.target.dataset.section)){cs.seen.push(e.target.dataset.section);st[id]=cs;localStorage.setItem('aft_course',JSON.stringify(st));updateRead()}}})},{threshold:.35});document.querySelectorAll('[data-section]').forEach(x=>obs.observe(x))}
function completeLesson(){if(!current)return;const id=requested(),s=JSON.parse(localStorage.getItem('aft100')||'{"done":[]}');s.done=s.done||[];if(!s.done.includes(id))s.done.push(id);localStorage.setItem('aft100',JSON.stringify(s));$('#completeBtn').textContent='✓ Abgeschlossen';$('#courseStatus').textContent='✓ Im 0→100-Pfad abgeschlossen';toast('Lektion im 0→100-Pfad abgeschlossen');setTimeout(()=>navigateCourse(1),700)}
function navigateCourse(dir){const id=requested(),i=COURSE_ORDER.indexOf(id),next=COURSE_ORDER[Math.max(0,Math.min(COURSE_ORDER.length-1,i+dir))];if(next&&next!==id)location.href='kurs.html?lesson='+encodeURIComponent(next)}
function updateNav(){const id=requested(),i=COURSE_ORDER.indexOf(id);$('#prevBtn').disabled=i<=0;$('#nextBtn').disabled=i<0||i>=COURSE_ORDER.length-1}
function toast(t){const n=document.createElement('div');n.style.cssText='position:fixed;right:18px;bottom:18px;background:#0f172a;color:#fff;padding:11px 14px;border-radius:12px;z-index:100;box-shadow:0 14px 40px rgba(0,0,0,.2)';n.textContent=t;document.body.appendChild(n);setTimeout(()=>n.remove(),1800)}
window.addEventListener('DOMContentLoaded',render);