const PHASES=[
{id:1,from:0,to:12,title:'Grundlagen verstehen',subtitle:'Anatomie · Physiologie · Prüfungslogik',source:'Annecke/Hohn Kap. 1.1–1.2',lessons:[
['exam','Prüfungslogik & Antwortstruktur','Wie das klinische Fachgespräch funktioniert'],['neurophys','Nervensystem','Anästhesierelevante Neurophysiologie'],['resp','Atemwege, Lunge & BGA','Ventilation, Oxygenierung und Säure-Basen-Haushalt'],['cardiophys','Herz-Kreislauf-Physiologie','Vorlast, Nachlast, Kontraktilität und Perfusion'],['renal','Nierenphysiologie','GFR, Volumen, Elektrolyte und Säure-Basen-Bezug'],['livergi','Leber & Gastrointestinaltrakt','Leberfunktion, Gerinnung und Aspirationsbezug'],['endocrine','Endokrinologie','Diabetes, Schilddrüse und Stressantwort']]},
{id:2,from:12,to:27,title:'Pharmakologie & Technik',subtitle:'Medikamente · Monitoring · Transfusion',source:'Annecke/Hohn Kap. 1.3–1.5',lessons:[
['hypnotics','Hypnotika','Propofol, Etomidat, Ketamin, Thiopental und Midazolam'],['opioids','Opioide','Wirkmechanismus, Kinetik und klinische Auswahl'],['nmb','Muskelrelaxanzien & Relaxometrie','Blockade, Monitoring und Antagonisierung'],['volatile','Volatile Anästhetika','MAC, Organwirkungen und klinische Anwendung'],['local','Lokalanästhetika','Na-Kanal-Blockade, Kinetik und Toxizität'],['adjuvants','Adjuvanzien & Nichtopioid-Analgetika','Multimodale Analgesie'],['vaso','Kardiovaskuläre Medikamente','Vasopressoren, Inotropika und Vasodilatatoren'],['monitoring','Mess- & Gerätetechnik','Monitoring verstehen statt Werte auswendig lernen'],['transfusion','Transfusionsmedizin & Gerinnung','Blutprodukte, POC-Gerinnung und Blutungsphysiologie']]},
{id:3,from:27,to:39,title:'Präoperativ sicher werden',subtitle:'Risiko · Begleiterkrankungen · Planung',source:'Annecke/Hohn Kap. 2',lessons:[
['preopcore','Präoperative Evaluation','Anamnese und Eingriff in ein konkretes Risiko übersetzen'],['cardiacrisk','Kardiale Begleiterkrankungen','KHK, Herzinsuffizienz, Klappenvitien und Stents'],['pulmrisk','Pulmonale Risiken & OSA','COPD, Asthma, Infekt und Schlafapnoe'],['organpreop','Niere, Leber & Stoffwechsel präoperativ','Organinsuffizienz und perioperative Konsequenzen'],['meds','Dauermedikation & Antikoagulation','Fortsetzen, pausieren oder umstellen begründen'],['fasting','Nüchternheit, Prämedikation & PONV','Aspirations- und PONV-Risiko planen'],['eras','ERAS / Fast Track','Prä-, intra- und postoperative Optimierung'],['consent','Aufklärung & Entscheidung','Einwilligung, Dringlichkeit und Dokumentation']]},
{id:4,from:39,to:64,title:'Intraoperativ beherrschen',subtitle:'Anästhesieführung · Regional · spezielle OPs',source:'Annecke/Hohn Kap. 3',lessons:[
['access','Zugänge, Monitoring & Lagerung','Monitoring und Gefäßzugänge dem Risiko anpassen'],['induction','Narkoseinduktion & Aufrechterhaltung','Einleitung anhand des Patientenrisikos planen'],['vent','Intraoperative Beatmung','VCV, PCV, PEEP, Compliance und Hypoxämie'],['fluids','Volumen- & Flüssigkeitstherapie','Euvolämie und Perfusion zielgerichtet steuern'],['emergence','Narkoseausleitung & Extubation','Extubation als Hochrisikoschritt'],['airway','Difficult Airway & RSI','Geplanter und unerwarteter schwieriger Atemweg'],['regionalper','Periphere Regionalanästhesie','Sonoanatomie, Indikationen und Komplikationen'],['neuraxial','Spinal- & Epiduralanästhesie','Neuraxiale Verfahren sicher auswählen'],['last','Lokalanästhetika-Toxizität (LAST)','Erkennen und behandeln'],['lap','Laparotomie, Laparoskopie & Ileus','Viszeralchirurgische Standardsituationen'],['thorax','Thoraxchirurgie & Ein-Lungen-Ventilation','DLT, HPV und Hypoxämie'],['vascular','Gefäßchirurgie','Karotis, Aorta und periphere Gefäße'],['ent','HNO / MKG','Shared Airway, Tumoren und Tracheotomie'],['uro','Urologie','TUR-Syndrom und große urologische Eingriffe'],['obgyn','Gynäkologie & Geburtshilfe','Sectio, PDK/SPA, Präeklampsie und PPH'],['remote','Außenbereiche','Endoskopie, MRT/CT und Interventionen'],['neuro','Neuroanästhesie','ICP, CPP und Neuroprotektion'],['ortho','Orthopädie & Unfallchirurgie','Regional, Blutung, Lagerung und Trauma']]},
{id:5,from:64,to:72,title:'Postoperativ kontrollieren',subtitle:'PACU · Schmerz · Komplikationen',source:'Annecke/Hohn Kap. 4',lessons:[
['pacu','Aufwachraum & Verlegung','Postoperative Probleme und richtige Destination'],['pain','Akutschmerz','Multimodale und verfahrensangepasste Analgesie'],['ponv','PONV','Risiko, Prophylaxe und Rescue'],['postcomp','Shivering, Laryngospasmus & Restblockade','Klassische AWR-Komplikationen'],['bleed','Postoperative Nachblutung','Erkennen, stabilisieren und Re-OP organisieren']]},
{id:6,from:72,to:80,title:'Kinder & ambulant',subtitle:'Kinderanästhesie · Neugeborene · Tageschirurgie',source:'Annecke/Hohn Kap. 5–6',lessons:[
['pedprep','Kinder: Vorbereitung & Nüchternheit','Altersspezifische Vorbereitung und Risiken'],['pedind','Kinder: Einleitung & Atemweg','Pädiatrische Atemwegsphysiologie'],['pedcomp','Kinder: Komplikationen & Flüssigkeit','Laryngospasmus, Bronchospasmus, PONV und Flüssigkeit'],['specialkids','Frühgeborene, Herzvitien & Neugeborene','Besondere Physiologie und Neugeborenenversorgung'],['ambulatory','Ambulante Anästhesie','Patientenselektion und sichere Entlassung']]},
{id:7,from:80,to:92,title:'Notfall & Intensiv',subtitle:'Schock · Sepsis · Reanimation · Trauma',source:'Annecke/Hohn Kap. 7 + Sonderhefte',lessons:[
['aspiration','Aspiration','Risiko, Akutmanagement und postoperative Konsequenzen'],['shock','Schock','Hypovolämisch, distributiv, kardiogen und obstruktiv'],['anaphylaxis','Anaphylaxie','Perioperative Anaphylaxie erkennen und priorisiert behandeln'],['sepsis','Sepsis & septischer Schock','Infektion, Organdysfunktion und Perfusion'],['cpr','Reanimation & Postreanimation','ALS-Logik, reversible Ursachen und Post-ROSC'],['acs','Akutes Koronarsyndrom','Perioperatives ACS erkennen und handeln'],['polytrauma','Polytrauma & SHT','Schockraum, Blutung und Neuroprotektion'],['icu','Allgemeine Intensivtherapie','Organunterstützung und tägliche Reevaluation'],['aki','Akutes Nierenversagen','AKI, Hyperkaliämie und Nierenersatzverfahren'],['burns','Verbrennungen','Atemweg, Flüssigkeit, Temperatur und Schmerz'],['mh','Maligne Hyperthermie','Frühzeichen, Trigger und Therapie'],['ards','ARDS','Lungenprotektive Beatmung und Eskalation']]},
{id:8,from:92,to:98,title:'50 Fallvignetten trainieren',subtitle:'Springer Facharzt-Training Heft 1 + 2',source:'Sonderheft 1 Fall 1–25 · Sonderheft 2 Fall 26–50',lessons:[
['cases1','Fallblock 1 · Fälle 1–5','Vorerkrankungen, Diabetes, Viszeral, Neuro, HNO'],['cases2','Fallblock 2 · Fälle 6–10','Airway, Trauma, Relaxierung, Volumen und Komplikationen'],['cases3','Fallblock 3 · Fälle 11–15','Pharmakologie, Regional, große OPs und Ileus'],['cases4','Fallblock 4 · Fälle 16–20','Awareness, COPD/BGA, Geburtshilfe, Neuro und Thorax'],['cases5','Fallblock 5 · Fälle 21–25','Blutung, MH, CPR, Delir und ARDS'],['cases6','Fallblock 6 · Fälle 26–30','Geriatrie, ZVK, Leber, Regional und Aufklärung'],['cases7','Fallblock 7 · Fälle 31–35','Whipple, TEP, Hygiene, Trauma und Kinder'],['cases8','Fallblock 8 · Fälle 36–40','Onkochirurgie, OSA, Gefäß und Schmerz'],['cases9','Fallblock 9 · Fälle 41–45','Aspiration, PONV, Sepsis und Rhythmusstörungen'],['cases10','Fallblock 10 · Fälle 46–50','CPR, Bewusstlosigkeit, Awareness, PDPH und Wirbelsäule']]},
{id:9,from:98,to:100,title:'Prüfungsreif werden',subtitle:'Protokolle · Mock Exams · letzte Lücken',source:'Prüfungsprotokolle + eigener Fehlerkatalog',lessons:[
['protocols','Protokoll-Radar & regionale Schwerpunkte','Wiederkehrende Themen priorisieren'],['mock1','Mock Exam 1 · 30 Minuten','Komplette Simulation ohne Hilfsmittel'],['mock2','Mock Exam 2 · Prüferwechsel','Unterbrechungen und Themenwechsel trainieren'],['final','Finaler 7-Tage-Sprint','Nur Schwächen, Algorithmen und mündliche Struktur']]}
];
const $=s=>document.querySelector(s);const state=()=>JSON.parse(localStorage.getItem('aft100')||'{"done":[]}');const save=s=>localStorage.setItem('aft100',JSON.stringify(s));const all=()=>PHASES.flatMap(p=>p.lessons.map(l=>({p,l})));const done=()=>state().done||[];const isDone=id=>done().includes(id);const pct=()=>Math.round(done().length/all().length*100);
function toggle(id){const s=state();s.done=s.done||[];s.done=s.done.includes(id)?s.done.filter(x=>x!==id):[...s.done,id];save(s);render();toast(s.done.includes(id)?'Einheit abgeschlossen ✓':'Einheit wieder geöffnet')}
function openCourse(id){location.href='kurs.html?lesson='+encodeURIComponent(id)}
function nextItem(){return all().find(x=>!isDone(x.l[0]))||null}
function openNext(){const n=nextItem();if(n)openCourse(n.l[0]);else toast('100 % – Lernpfad abgeschlossen')}
function render(){const items=all(),d=done(),p=pct(),n=nextItem()||items[items.length-1];$('#pct').textContent=p+'%';$('#mainBar').style.width=p+'%';$('#doneCount').textContent=d.length;$('#totalCount').textContent=items.length;$('#remainCount').textContent=items.length-d.length;$('#currentPhase').textContent=n.p.id;$('#currentPhaseName').textContent=n.p.title;const prof=JSON.parse(localStorage.getItem('aft2')||'{}');const days=prof.examDate?Math.max(0,Math.ceil((new Date(prof.examDate+'T12:00:00')-Date.now())/86400000)):null;$('#examDays').textContent=days==null?'–':days;const weeks=days?Math.max(1,days/7):16;$('#weeklyTarget').textContent=Math.max(1,Math.ceil((items.length-d.length)/weeks));$('#nextPhase').textContent='PHASE '+n.p.id+' · '+n.p.from+'–'+n.p.to+'%';$('#nextTitle').textContent=n.l[1];$('#nextOutcome').textContent=n.l[2];$('#nextTags').innerHTML=`<span class="tag source">${n.p.source}</span><span class="tag">Vollkurs im Browser</span>`;$('#phaseNav').innerHTML=PHASES.map(p=>`<button class="${p.id===n.p.id?'on':''}" onclick="document.getElementById('phase-${p.id}').scrollIntoView({behavior:'smooth'})">${p.id}. ${p.title}</button>`).join('');$('#phaseList').innerHTML=PHASES.map(p=>{const pd=p.lessons.filter(l=>d.includes(l[0])).length,pp=Math.round(pd/p.lessons.length*100);return `<section class="card phase" id="phase-${p.id}"><div class="phaseHead"><div class="phaseNum">${p.id}</div><div><div class="eyebrow">${p.subtitle}</div><h3>${p.title}</h3><div class="small muted">${p.source} · ${pd}/${p.lessons.length} abgeschlossen</div></div><div class="phaseRange">${p.from} → ${p.to}%</div></div><div class="phasebar"><span style="width:${pp}%"></span></div><div class="lessons">${p.lessons.map(l=>`<div class="lesson ${d.includes(l[0])?'done':''}"><button class="check" onclick="toggle('${l[0]}')">${d.includes(l[0])?'✓':''}</button><div><strong>${l[1]}</strong><span class="small muted">${l[2]}</span><div class="status">📖 Kurs lesen → Wissen prüfen → abschließen</div></div><button class="learn" onclick="openCourse('${l[0]}')">Kurs öffnen →</button></div>`).join('')}</div></section>`}).join('')}
function resetPath(){if(confirm('Den kompletten 0→100-Fortschritt wirklich auf 0 % zurücksetzen?')){save({done:[]});render();toast('Lernpfad auf 0 % gesetzt')}}function toast(t){const n=document.createElement('div');n.className='toast';n.textContent=t;document.body.appendChild(n);setTimeout(()=>n.remove(),1800)}render();